export enum RequestType {
    MANUAL_CHECK_IN = 'MANUAL_CHECK_IN',
    MANUAL_CHECK_OUT = 'MANUAL_CHECK_OUT',
    DAILY_LEAVE = 'DAILY_LEAVE',
    HOURLY_LEAVE = 'HOURLY_LEAVE',
    SICK_LEAVE = 'SICK_LEAVE',
    // OVERTIME = 'OVERTIME'
}