name: Deploy Nest.js Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/backend.linchpin.exir
            git pull origin main
            npm install
            npm run build
            pm2 stop all || true  # Stop any currently running processes
            pm2 start dist/main.js --name "nestjs-app" # Start the backend app with pm2 (adjust the entry point if needed)
            pm2 save  # Save the process list
            pm2 startup # Ensure PM2 restarts on system boot
